module.exports = {
    name: 'ja',
    description: "JASKSJAKJKAJSKJASKAJSKJASKAJSKAJSKAJSKAJS!",
    execute(message, args){
        message.reply('JASKSJAKJKAJSKJASKAJSKJASKAJSKAJSKAJSKAJSJASKSJAKJKAJSKJASKAJSKJASKAJSKAJSKAJSKAJSJASKSJAKJKAJSKJASKAJSKJASKAJSKAJSKA');
        }
    }